// <auto-generated />
using ConfigController.EntityConfiguration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigController.Migrations
{
    [DbContext(typeof(KurosawaConfigContext))]
    partial class KurosawaConfigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ConfigController.Models.BaseConfig", b =>
                {
                    b.Property<uint>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("IdDono")
                        .HasColumnName("IDDono")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnName("Prefix")
                        .HasColumnType("TEXT")
                        .HasMaxLength(16);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("TokenBot")
                        .HasColumnType("TEXT");

                    b.HasKey("Cod");

                    b.ToTable("BaseConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
