// <auto-generated />
using ConfigController.EntityConfiguration;
using ConfigController.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfigController.Migrations
{
    [DbContext(typeof(KurosawaConfigContext))]
    partial class KurosawaConfigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ConfigController.Models.ApiConfig", b =>
                {
                    b.Property<uint>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnName("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Cod");

                    b.ToTable("ApiConfig");
                });

            modelBuilder.Entity("ConfigController.Models.BaseConfig", b =>
                {
                    b.Property<uint>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("IdDono")
                        .HasColumnName("IDDono")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasColumnName("Prefix")
                        .HasColumnType("TEXT")
                        .HasMaxLength(16);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("TokenBot")
                        .HasColumnType("TEXT");

                    b.HasKey("Cod");

                    b.ToTable("BaseConfig");
                });

            modelBuilder.Entity("ConfigController.Models.DBConfig", b =>
                {
                    b.Property<ushort>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnName("Database")
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnName("IP")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Porta")
                        .HasColumnName("Porta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("Senha")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnName("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Cod");

                    b.ToTable("DBConfig");
                });

            modelBuilder.Entity("ConfigController.Models.StatusConfig", b =>
                {
                    b.Property<uint>("Cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Cod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusJogo")
                        .IsRequired()
                        .HasColumnName("StatusJogo")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("StatusUrl")
                        .HasColumnName("StatusUrl")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<TipoDeStatus>("TipoDeStatus")
                        .HasColumnName("TipoDeStatus")
                        .HasColumnType("integer");

                    b.HasKey("Cod");

                    b.ToTable("StatusConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
