version: "3"
services:
    bot:
        image: ghcr.io/fardragi/kurosawadia:latest
        container_name: kurosawa_dia_bot
        depends_on:
            db:
                condition: service_healthy
            ssh:
                condition: service_started
        networks:
            - kurosawa_dia
        environment:
            KUROSAWA_TOKEN: ${KUROSAWA_TOKEN}
            KUROSAWA_BOT_ID: ${KUROSAWA_BOT_ID}
            KUROSAWA_WEEB_API_TOKEN: ${KUROSAWA_WEEB_API_TOKEN}
            KUROSAWA_DATABASE_CONNECTION_STRING: mysql://root:${KUROSAWA_DATABASE_PASSWORD}@kurosawa_dia_db:3306
            KUROSAWA_DATABASE_NAME: ${KUROSAWA_DATABASE_NAME}
            KUROSAWA_DANBOORU_TOKEN: ${KUROSAWA_DANBOORU_TOKEN}
    db:
        image: mariadb:10.5
        container_name: kurosawa_dia_db
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${KUROSAWA_DATABASE_PASSWORD}
        networks:
            - kurosawa_dia
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
            interval: 10s
            timeout: 5s
            retries: 5
    ssh:
        container_name: kurosawa_dia_ssh
        build:
            context: ./docker
            dockerfile: ssh.Dockerfile
        networks:
            - kurosawa_dia
        ports:
            - "127.0.0.1:2222:22"
networks:
    kurosawa_dia:
        driver: bridge
volumes:
    mariadb:
