version: "3.9"
services:
    bot:
        image: ghcr.io/fardragi/kurosawadia:1.4.4
        container_name: kurosawa_dia_bot
        restart: always
        depends_on:
            db:
                condition: service_healthy
        environment:
            KUROSAWA_TOKEN: ${KUROSAWA_TOKEN}
            KUROSAWA_BOT_ID: ${KUROSAWA_BOT_ID}
            KUROSAWA_WEEB_API_TOKEN: ${KUROSAWA_WEEB_API_TOKEN}
            KUROSAWA_DATABASE_CONNECTION_STRING: mysql://root:${KUROSAWA_DATABASE_PASSWORD}@kurosawa_dia_db:3306
            KUROSAWA_DATABASE_NAME: ${KUROSAWA_DATABASE_NAME}
            KUROSAWA_DANBOORU_TOKEN: ${KUROSAWA_DANBOORU_TOKEN}
    db:
        image: mariadb:10.5
        container_name: kurosawa_dia_db
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${KUROSAWA_DATABASE_PASSWORD}
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "--silent" ]
            interval: 10s
            timeout: 5s
            retries: 5
    ssh:
        container_name: kurosawa_dia_ssh
        restart: always
        build:
            context: ./docker
            dockerfile: ssh.Dockerfile
            args:
                password: ${SSH_PASSWORD}
                username: ${SSH_USERNAME}
        ports:
            - "127.0.0.1:2222:22"

volumes:
    mariadb:
